# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('params', models.CharField(max_length=400)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.CharField(max_length=400)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Repository')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='rep_views',
            field=models.ManyToManyField(to='projects.RepositoryView'),
        ),
        migrations.AddField(
            model_name='project',
            name='subprojects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
        migrations.AddField(
            model_name='organization',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
        migrations.AddField(
            model_name='organization',
            name='suborgs',
            field=models.ManyToManyField(to='projects.Organization'),
        ),
    ]
