#!/bin/bash

echo "Running Bestiary"

git clone https://github.com/acs/bestiary.git
cd bestiary/django_bestiary

# Create the data models
python3 manage.py makemigrations
python3 manage.py migrate

# Create the initial admin user: admin/admin
PYTHONPATH=. django_bestiary/create_admin_superuser.py

# Import some projects files as samples
PYTHONPATH=. projects/bestiary_import.py -o Release -f projects/projects-release.json 

# Run the MEditor service
# python3 manage.py runserver 0.0.0.0:8000
gunicorn django_bestiary.wsgi --bind 0.0.0.0:8000

