# Generated by Django 2.1 on 2020-05-25 14:34

import bestiary.core.models
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import grimoirelab_toolkit.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecosystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', bestiary.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', bestiary.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('name', models.CharField(help_text='Ecosystem name', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Ecosystem title', max_length=80, null=True)),
                ('description', models.CharField(help_text='Brief text describing the ecosystem', max_length=128, null=True)),
            ],
            options={
                'db_table': 'ecosystems',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('ouid', models.CharField(help_text='Operation unique identifier', max_length=128, primary_key=True, serialize=False)),
                ('op_type', models.CharField(choices=[('ADD', 'ADD'), ('DELETE', 'DELETE'), ('UPDATE', 'UPDATE')], help_text='Operation type (`ADD`, `DELETE` or `UPDATE`)', max_length=128)),
                ('entity_type', models.CharField(help_text='Type of the main entity involved in the operation', max_length=128)),
                ('target', models.CharField(help_text='Identifier of the targeted entity in the operation', max_length=128)),
                ('timestamp', models.DateTimeField(help_text='Datetime when the operation is performed')),
                ('args', django_mysql.models.JSONField(default=dict, help_text='Main input arguments when performing the operation')),
            ],
            options={
                'db_table': 'operations',
                'ordering': ('timestamp', 'ouid', 'trx'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', bestiary.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', bestiary.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('name', models.CharField(help_text='Project name', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Project title', max_length=80, null=True)),
                ('parent_project', models.ForeignKey(help_text='Parent project', null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='subprojects', to='core.Project')),
                ('ecosystem', models.ForeignKey(help_text='Ecosystem', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ecosystem')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tuid', models.CharField(help_text='Transaction unique identifier', max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the method creating the transaction', max_length=128)),
                ('created_at', models.DateTimeField(help_text='Datetime when the transaction was created')),
                ('closed_at', models.DateTimeField(help_text='Datetime when the transaction was closed', null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Boolean value, `True` if the transaction is closed')),
                ('authored_by', models.CharField(help_text='Username from who created the transaction', max_length=128, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ('created_at', 'tuid'),
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='trx',
            field=models.ForeignKey(db_column='tuid', help_text='Transaction (context) where this operation is performed', on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.Transaction'),
        ),
    ]
