# Generated by Django 2.1 on 2020-05-19 12:44

import bestiary.core.models
from django.db import migrations, models
import django.db.models.deletion
import grimoirelab_toolkit.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', bestiary.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', bestiary.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('name', models.CharField(help_text='Project name', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Project title', max_length=80, null=True)),
                ('parent_project', models.ForeignKey(help_text='Parent project', null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.Project')),
                ('ecosystem', models.ForeignKey(help_text='Ecosystem', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ecosystem')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ('name',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name',)},
        ),
    ]
