# Generated by Django 3.1 on 2021-08-02 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datasources_datasets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ecosystem',
            field=models.ForeignKey(default=1, help_text='Ecosystem', on_delete=django.db.models.deletion.CASCADE, to='core.ecosystem'),
            preserve_default=False,
        ),
    ]
