# Generated by Django 3.1 on 2021-09-21 09:19

import bestiary.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grimoirelab_toolkit.datetime


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_project_ecosystem_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', bestiary.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', bestiary.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('name', models.CharField(help_text='Name of the token.', max_length=80)),
                ('token', bestiary.core.models.EncryptedField(help_text='token for authentication to a backend.', max_length=364)),
                ('datasource', models.ForeignKey(help_text='Related data source', on_delete=django.db.models.deletion.CASCADE, to='core.datasourcetype')),
                ('user', models.ForeignKey(help_text='user allowed to user this token.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credentials',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
